[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-arg=--no-entry",
]

[build]
target-dir = "target"

# Enable getrandom's wasm_js feature for wasm32 targets
[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))']
rustflags = ["--cfg=getrandom_backend=\"wasm_js\""]

# Android NDK linker configuration
# These linkers will be used when ANDROID_NDK_HOME is set
[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"

[target.i686-linux-android]
linker = "i686-linux-android21-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"
