# Jekyll Configuration for jsoneval-rs Documentation

title: jsoneval-rs
tagline: High-performance JSON Logic evaluation library
description: >-
  Blazing-fast JSON Logic evaluator built in Rust with 80+ operators.
  Comprehensive operator documentation, multiple language bindings, and deployment guides.

url: "https://byrizki.github.io"
baseurl: "/jsoneval-rs"

# Theme
theme: jekyll-theme-cayman

# GitHub repository
github:
  repository_url: https://github.com/byrizki/jsoneval-rs

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
