# Jekyll Configuration for json-eval-rs Documentation

title: json-eval-rs Documentation
tagline: High-performance JSON Logic evaluation library with 80+ operators
description: >-
  json-eval-rs is a blazing-fast JSON Logic evaluator with comprehensive operator documentation,
  bindings, and deployment guides.

url: "https://byrizki.github.io"
baseurl: "/json-eval-rs"

lang: en
timezone: Asia/Jakarta

remote_theme: "cotes2020/jekyll-theme-chirpy@v6.7.0"

theme_mode: light

# Site metadata
author: byrizki
twitter:
  username: byrizki
  card: summary
github:
  username: byrizki
  repository: json-eval-rs

# Pagination & archive
paginate: 10
paginate_path: "/page:num/"
collections:
  operators:
    output: true
    permalink: /:collection/:name

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: page
      toc: true

# Navigation tabs (displayed by Chirpy in the top bar)
tabs:
  - name: Home
    path: /
    icon: "fas fa-home"
  - name: Quick Reference
    path: /OPERATORS_SUMMARY
    icon: "fas fa-book"
  - name: Operators
    path: /operators-core
    icon: "fas fa-project-diagram"

# Include/Exclude
include:
  - README.md
  - OPERATORS_SUMMARY.md
  - operators-*.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Analytics (set your provider IDs if available)
google_analytics:
  id:

# Sitemap configuration for Chirpy
sitemap:
  exclude:
    - /assets/
    - /tabs/
