# Jekyll Configuration for json-eval-rs Documentation

title: json-eval-rs
description: >-
  High-performance JSON Logic evaluation library with 80+ operators.
  Blazing-fast evaluator built in Rust with comprehensive operator documentation,
  bindings, and deployment guides.

url: "https://byrizki.github.io"
baseurl: "/json-eval-rs"

theme: jekyll-theme-minimal

# GitHub repository
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/byrizki/json-eval-rs
  owner_name: byrizki
  owner_url: https://github.com/byrizki

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
