name: Build Bindings

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ created ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # Build native libraries for all platforms
  build-native:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: libjson_eval_rs.so
            build_features: ffi
          
          # Windows x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: json_eval_rs.dll
            build_features: ffi
          
          # macOS x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: libjson_eval_rs.dylib
            build_features: ffi
          
          # macOS ARM64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: libjson_eval_rs.dylib
            build_features: ffi
          
          # iOS ARM64 (device)
          - os: macos-latest
            target: aarch64-apple-ios
            artifact_name: libjson_eval_rs.a
            build_features: ffi
          
          # iOS x86_64 (simulator)
          - os: macos-latest
            target: x86_64-apple-ios
            artifact_name: libjson_eval_rs.a
            build_features: ffi

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build native library
      run: cargo build --release --target ${{ matrix.target }} --features ${{ matrix.build_features }}
    
    - name: Upload native library artifact
      uses: actions/upload-artifact@v4
      with:
        name: native-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        if-no-files-found: error

  # Build C# NuGet package
  build-csharp:
    needs: build-native
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Download Linux native library
      uses: actions/download-artifact@v4
      with:
        name: native-x86_64-unknown-linux-gnu
        path: target/x86_64-unknown-linux-gnu/release/
    
    - name: Download Windows native library
      uses: actions/download-artifact@v4
      with:
        name: native-x86_64-pc-windows-msvc
        path: target/x86_64-pc-windows-msvc/release/
    
    - name: Download macOS x64 native library
      uses: actions/download-artifact@v4
      with:
        name: native-x86_64-apple-darwin
        path: target/x86_64-apple-darwin/release/
    
    - name: Download macOS ARM64 native library
      uses: actions/download-artifact@v4
      with:
        name: native-aarch64-apple-darwin
        path: target/aarch64-apple-darwin/release/
    
    - name: Build NuGet package
      run: |
        cd bindings/csharp
        dotnet pack -c Release
    
    - name: Upload NuGet package
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: bindings/csharp/bin/Release/*.nupkg
        if-no-files-found: error

  # Build Web/WASM package
  build-web:
    runs-on: ubuntu-latest
    
    env:
      RUSTFLAGS: "--cfg=getrandom_backend=\"wasm_js\""
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-wasm-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build WASM for bundler
      run: wasm-pack build --target bundler --out-dir bindings/web/packages/bundler/pkg --features wasm
    
    - name: Build WASM for Node.js
      run: wasm-pack build --target nodejs --out-dir bindings/web/packages/node/pkg --features wasm
    
    - name: Install web dependencies
      run: |
        cd bindings/web
        npm install
    
    - name: Package web binding
      run: |
        cd bindings/web
        npm pack
    
    - name: Upload web package
      uses: actions/upload-artifact@v4
      with:
        name: web-package
        path: bindings/web/*.tgz
        if-no-files-found: error
    
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-modules
        path: |
          bindings/web/packages/bundler/pkg/
          bindings/web/packages/node/pkg/

  # Build Android JNI libraries
  build-android-jni:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - arm64-v8a
          - armeabi-v7a
          - x86
          - x86_64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26c
        add-to-path: true
    
    - name: Install cargo-ndk
      run: cargo install cargo-ndk
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-android-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build Android JNI library
      run: |
        cargo ndk -t ${{ matrix.target }} -o bindings/react-native/android/src/main/jniLibs build --release --features ffi
    
    - name: Upload Android JNI artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-jni-${{ matrix.target }}
        path: bindings/react-native/android/src/main/jniLibs/${{ matrix.target }}/
        if-no-files-found: error
  
  # Build React Native package
  build-react-native:
    needs: [build-native, build-android-jni]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Download desktop native libraries
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
    
    - name: Download Android JNI libraries
      uses: actions/download-artifact@v4
      with:
        pattern: android-jni-*
        path: bindings/react-native/android/src/main/jniLibs/
    
    - name: Organize native libraries
      run: |
        # Create iOS framework directory
        mkdir -p bindings/react-native/ios/libs
        
        # Copy iOS libraries if they exist
        if [ -d "artifacts/native-aarch64-apple-ios" ]; then
          cp -r artifacts/native-aarch64-apple-ios/* bindings/react-native/ios/libs/ || true
        fi
        
        if [ -d "artifacts/native-x86_64-apple-ios" ]; then
          cp -r artifacts/native-x86_64-apple-ios/* bindings/react-native/ios/libs/ || true
        fi
        
        echo "Native libraries organized"
        ls -R bindings/react-native/android/src/main/jniLibs/ || true
        ls -R bindings/react-native/ios/libs/ || true
    
    - name: Install React Native dependencies
      run: |
        cd bindings/react-native
        npm install
    
    - name: Build TypeScript
      run: |
        cd bindings/react-native
        npm run prepare || echo "Prepare script not found, skipping"
    
    - name: Install example dependencies
      run: |
        cd bindings/react-native/examples/rncli
        npm install || echo "Example dependencies installation skipped"
    
    - name: Package React Native binding
      run: |
        cd bindings/react-native
        npm pack
    
    - name: Upload React Native package
      uses: actions/upload-artifact@v4
      with:
        name: react-native-package
        path: bindings/react-native/*.tgz
        if-no-files-found: error

  # Run tests
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run tests
      run: cargo test --all-features
    
    - name: Run tests (release mode)
      run: cargo test --release --all-features

  # Create release with all artifacts
  create-release:
    if: github.event_name == 'release'
    needs: [build-native, build-android-jni, build-csharp, build-web, build-react-native, test]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: release-artifacts/
    
    - name: Create release archives
      run: |
        cd release-artifacts
        
        # Archive native libraries
        tar -czf native-linux-x64.tar.gz native-x86_64-unknown-linux-gnu/
        tar -czf native-windows-x64.tar.gz native-x86_64-pc-windows-msvc/
        tar -czf native-macos-x64.tar.gz native-x86_64-apple-darwin/
        tar -czf native-macos-arm64.tar.gz native-aarch64-apple-darwin/
        
        # Archive WASM modules
        tar -czf wasm-modules.tar.gz wasm-modules/
    
    - name: Upload release archives
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release-artifacts/*.tar.gz
          release-artifacts/nuget-package/*.nupkg
          release-artifacts/web-package/*.tgz
          release-artifacts/react-native-package/*.tgz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Summary job
  summary:
    if: always()
    needs: [build-native, build-android-jni, build-csharp, build-web, build-react-native, test]
    runs-on: ubuntu-latest
    
    steps:
    - name: Build Summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Native Libraries" >> $GITHUB_STEP_SUMMARY
        echo "✅ Desktop platforms (Linux, Windows, macOS)" >> $GITHUB_STEP_SUMMARY
        echo "✅ iOS (device & simulator)" >> $GITHUB_STEP_SUMMARY
        echo "✅ Android (arm64-v8a, armeabi-v7a, x86, x86_64)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Bindings Packages" >> $GITHUB_STEP_SUMMARY
        echo "✅ C# NuGet package created" >> $GITHUB_STEP_SUMMARY
        echo "✅ Web/WASM package created" >> $GITHUB_STEP_SUMMARY
        echo "✅ React Native package created" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Tests" >> $GITHUB_STEP_SUMMARY
        echo "✅ All tests passed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "All artifacts are available for download from this workflow run." >> $GITHUB_STEP_SUMMARY
